### ISSUE TITLE
namespace conflict

### ISSUE THREAD

**Issue by chenharryhua** [julianpeeters/avrohugger#131]
scala.jdk.CollectionConverters in _scala-collection-compat_2.12:2.1.2.jar looks like conflict with the https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala-2.12/scala/jdk/package.scala.

a runtime error will be thrown:
`[error] java.lang.NoSuchMethodError: scala.jdk.CollectionConverters$.RichConcurrentHashMap(Ljava/util/concurrent/ConcurrentHashMap;)Lscala/jdk/CollectionConverters$RichConcurrentHashMap;
[error] 	at avrohugger.stores.ClassStore.<init>(ClassStore.scala:14)
[error] 	at avrohugger.Generator.<init>(Generator.scala:25)`

the error can be reproduced by version 1.0.0-RC22.(scala version: 2.12)
avrohugger version 1.0.0-RC21 is OK

**Comment by TidyMaze** [comment]
same issue here, I wish it could be fixed 👍

**Comment by kgupta26** [comment]
Even `1.0.0-RC21` doesn't work for me.
scalaVersion := "2.12.11"
sbt.version=1.3.13

```
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.julianpeeters:sbt-avrohugger:1.0.0-RC21 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.julianpeeters:sbt-avrohugger;sbtVersion=1.0;scalaVersion=2.12:1.0.0-RC21
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/julianpeeters/sbt-avrohugger_2.12_1.0/1.0.0-RC21/sbt-avrohugger-1.0.0-RC21.pom
[error]   not found: /Users/mm10444/.ivy2/local/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/1.0.0-RC21/ivys/ivy.xml
[error]   not found: http://repo.artima.com/releases/com/julianpeeters/sbt-avrohugger_2.12_1.0/1.0.0-RC21/sbt-avrohugger-1.0.0-RC21.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/1.0.0-RC21/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/1.0.0-RC21/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.julianpeeters:sbt-avrohugger;sbtVersion=1.0;scalaVersion=2.12:1.0.0-RC21
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/julianpeeters/sbt-avrohugger_2.12_1.0/1.0.0-RC21/sbt-avrohugger-1.0.0-RC21.pom
[error]   not found: /Users/mm10444/.ivy2/local/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/1.0.0-RC21/ivys/ivy.xml
[error]   not found: http://repo.artima.com/releases/com/julianpeeters/sbt-avrohugger_2.12_1.0/1.0.0-RC21/sbt-avrohugger-1.0.0-RC21.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.julianpeeters/sbt-avrohugger/scala_2.12/sbt_1.0/1.0.0-RC21/ivys/ivy.xml

```
