### ISSUE TITLE
Avro serialization failed for optional enums encoded as Scala string

### ISSUE THREAD

**Issue by improved-broccoli** [julianpeeters/avrohugger#144]
Given that case class generated, with sbt-avrohugger 2.0.0-RC21 from an Avro schema:

```scala
import java.io.ByteArrayOutputStream
import org.apache.avro.{AvroRuntimeException, Schema}
import org.apache.avro.Schema.Parser
import org.apache.avro.generic.GenericData.EnumSymbol
import org.apache.avro.io._
import org.apache.avro.specific._
import scala.annotation.switch

case class AvroOptionalEnumTest(var myenum: Option[String] = None) extends SpecificRecordBase {

  def get(field$: Int): AnyRef =
    (field$: @switch) match {
      case 0 =>
        (myenum match {
          case Some(x) => new EnumSymbol(getSchema.getFields.get(field$).schema, x)
          case None => null
        }).asInstanceOf[AnyRef]
      case _ => new AvroRuntimeException("Bad index")
    }

  def put(field$: Int, value: Any): Unit =
    (field$: @switch) match {
      case 0 => this.myenum = {
        value match {
          case null => None
          case _ => Some(value.toString)
        }
      }
    }

  def getSchema: Schema = AvroOptionalEnumTest.SCHEMA$

}

object AvroOptionalEnumTest {

  val SCHEMA$ = new Parser().parse("{\"type\":\"record\",\"name\":\"AvroOptionalEnumTest\",\"namespace\":\"foo.bar\",\"fields\":[{\"name\":\"myenum\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"MyEnum\",\"symbols\":[\"FOO\",\"BAR\"]}],\"default\":null}]}")

}
```

Trying to serialize it like this:
```
val avroOptionalEnumTestData = AvroOptionalEnumTest(Some("FOO"))
val out = new ByteArrayOutputStream()
val writer = new SpecificDatumWriter[AvroOptionalEnumTest](AvroOptionalEnumTest.SCHEMA$)
writer.write(avroOptionalEnumTestData, EncoderFactory.get.binaryEncoder(out, null))
```

Result in this error:
```
org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"enum","name":"MyEnum","namespace":"foo.bar","symbols":["FOO","BAR"]}]: FOO
  at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:878)
  at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:272)
  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:143)
  at org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:98)
  at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
  at org.apache.avro.specific.SpecificDatumWriter.writeRecord(SpecificDatumWriter.java:83)
  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
  ... 39 elided
```

This is because of this line specifically : `getSchema.getFields.get(field$).schema` which returns the schema of the union in the case of an optional enum as String.
Instead, it should returns the schema of the inner enum like this:
```
            val unionSchema = getSchema.getFields.get(field$).schema // Same as current
            new EnumSymbol(unionSchema.getTypes.get(unionSchema.getIndexNamed("foo.bar.MyEnum")), x)
```
`"foo.bar.MyEnum"` is a dynamic value depending on the enum.

**Comment by julianpeeters** [comment]
Thanks very much, your solution is now included in avrohugger 1.0.0-RC27 and sbt-avrohugger RC27
