### ISSUE TITLE
Generating generic model classes results in StackOverflow error

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/avrohugger#26]
I will investigate this a bit more later on, just pasting the stack trace for now.

This happens after generating the records. The project mainly contains records and some helper classes. It is the Scala.js part of a shared model project, the JVM part (using SpecificRecord) compiles just fine.

``` scala
info] Compiling 89 Scala sources to /Users/.../Workspace/.../model/.js/target/scala-2.11/classes...
java.lang.StackOverflowError
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:680)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4523)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4579)
        ...
```

**Comment by julianpeeters** [comment]
Doesn't ring a bell.

A typer error is pretty weird. I've run into them on only three occasions. I've seen a compiler bug like that in Scala 2.10, but then I would expect the Specific to trip it as well. Or Maybe Improper trees are generated? But your classes are being generated OK? Do they look normal/clean, or corrupted (weird symbols, anonymous classes visible). Or perhaps the typer is choking the order of nested or recursive definitions? The defineClass ClassLoader error suggests a duplicate .class file, but in that case I believe there would be an error message to that effect. Just throwing out ideas.

**Comment by julianpeeters** [comment]
I should clarify that I haven't been able to reproduce this, the generic scripted tests seem to work fine as a standalone project.

**Comment by mariussoutier** [comment]
The classes look fine, IntelliJ doesn't complain either.

**Comment by mariussoutier** [comment]
And it's only happening in the JS-project, not the JVM one, which I find very weird.

**Comment by mariussoutier** [comment]
I found the avdl that is causing trouble, it's a rather large one...

**Comment by mariussoutier** [comment]
Oh I think I broke the new case class limit of 104 parameters. Strange that it works when extending specific record though, apparently it's because we override the default constructor.

**Comment by mariussoutier** [comment]
I assumed they completely removed the arity-limit on case classes.

**Comment by mariussoutier** [comment]
Ah this only seems to concern Scala.js.

**Comment by julianpeeters** [comment]
Oh, no, it wouldn't be a small one :)

Quite interesting tho.

**Comment by mariussoutier** [comment]
See https://github.com/scala-js/scala-js/issues/2132#issuecomment-167050357.
